### ISSUE TITLE
where the model code?

### ISSUE THREAD

**Issue by yuan243212790** [ViTAE-Transformer/ViTPose#38]
I can not find the vitpose model in mmpose, can anybody know?

**Comment by WT-UCAS** [comment]
I also want to ask the question

**Comment by hao14293** [comment]
I also want to ask the question

**Comment by alecda573** [comment]
@yuan243212790 @WT-UCAS @hao14293 take this with a grain of salt cause I just started looking through the repo and the paper. But the backbone is ViT.py and they trained 3 models in the paper based off an image is worth 16x16 words. There are the Base, Large, and Huge models (which means you can modify ViT.py class Vit(BaseBackbone) args for 3/4 parameters that differentiate the Base, Large, and Huge models (hidden size, mlp size, heads all that is missing in layers). 

Also, looking through the paper, they seem to use a simple decoder which is probably coming from mmpose.models.heads.deconv_head.py

The actual building of the model seems to be happening from two main places: mmcv (which you install with this repo) and then inside, mmcv.cnn builder.py and teh config file that sets the hyperparameters to construct the model from the ViT and deconv_head can be found  in ViTPose/configs/body/2d_kpt_sview_rgb_img/topdown_heamap/coco 

Hopefully this helps you get started in your search. I would love to hear from any of the contributors as too how accurate this is. 
 @Annbless @AK391

**Comment by Annbless** [comment]
The different configurations of our models can be found in the [folder](https://github.com/ViTAE-Transformer/ViTPose/tree/main/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco). In each config file, there is a dictionary named `model`, which contains two sub-dictionaries named `backbone` and `keypoint head`, which define the exact structure of the backbone networks and prediction heads. The structure of the models described using the `backbone` dictionary can be found in the [`mmpose/models/backbones/`](https://github.com/ViTAE-Transformer/ViTPose/tree/main/mmpose/models/backbones) folders. Similarly, the exact structure of the keypoint head can be found in [`mmpose/models/heads/`](https://github.com/ViTAE-Transformer/ViTPose/tree/main/mmpose/models/heads).

**Comment by MaxTeselkin** [comment]
@Annbless Hi! Thanks for ViTPose. Can you please upload an example of using ViTPose via mmpose? I checked https://github.com/ViTAE-Transformer/ViTPose/blob/main/demo/MMPose_Tutorial.ipynb , but in this tutorial there are models which are already implemented in mmpose, and I can't use ViTPose like that. As far as I understood, to use ViTPose in mmpose, it necessary to firstly define backbone and head classes using .register_module() method, and after that pass ViTPose config to init_pose_model(). I am trying to do so, but I'm stuck in AttributeError: 'NoneType' object has no attribute '__name__', which I get every time when I run MODELS = Registry(
    'models', build_func=build_model_from_cfg, parent=MMCV_MODELS)
Here is code with my attempts of using ViTPose in mmpose: https://www.kaggle.com/maximteselkin/hps-via-vitpose
I will be really grateful if you can upload any example of using ViTPose via mmpose, because I don't understand what to do with this error.

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have any further questions, please feel free to re-open it.
