### ISSUE TITLE
Will this model work with unseen data?

### ISSUE THREAD

**Issue by bs97** [ViTAE-Transformer/ViTPose#45]
Will this model work with unseen data (in the wild pose estimation) or does it require further training outside the COCO/AIC/MPII/CrowdPose datasets?

**Comment by Annbless** [comment]
For now, the model should be used in samples whose definition of keypoints should be the same in the train set. It can predict the keypoints for humans on unseen data. However, for the keypoint estimation of cars,  I'm afraid that it can not support such estimation since we do not have such output heads.
