### ISSUE TITLE
Inference time varies with the number of persons in the image.

### ISSUE THREAD

**Issue by dinusha94** [ViTAE-Transformer/ViTPose#65]
Hi, This is an amazing pose estimator we have tried so far, I am running  VITPose in jetson AGX Orin (after converting to tensorRT), and when I checked the inference FPS it changes with the number of persons in the image, 

My question is how do you measure the throughput mentioned in the graph in the readme? and is there any way to mitigate this variable delay?

**Comment by Annbless** [comment]
It is because ViTPose follows the top-down pose estimation pipeline, where the inference time is related to the number of people in the images since it needs to predict each person in the image independently. We follow the common practice to measure the throughput, where the images refer to one person per image case.

**Comment by Annbless** [comment]
It seems there are no further questions. I will close this issue temporarily. If you have some further questions, please feel free to re-open it.
