### ISSUE TITLE
MMCV version not compatible with mmdet

### ISSUE THREAD

**Issue by ZhengdiYu** [ViTAE-Transformer/ViTPose#97]
I am trying to run your demo on image with mmdet.

I installed the environment by running your recommended command:
```
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
git checkout v1.3.9
MMCV_WITH_OPS=1 pip install -e .
cd ..
git clone https://github.com/ViTAE-Transformer/ViTPose.git
cd ViTPose
pip install -v -e .
pip install timm==0.4.9 einops
```
After that, I installed mmdet by `pip installed mmdet`. It threw: `ModuleNotFoundError: No module named 'mmengine'`. Then I run `pip install mmengine` and finally, the error became:
`AssertionError: MMCV==1.3.9 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.`

Do you have any suggestions? It seems the current mmcv in this repo is not compatible with any valid mmdet version. I also tried installing another version of mmdet==2.16.0. But it still didn't work and raised `ModuleNotFoundError: No module named 'mmcv._ext'` .

It seems that the problem was all about the mmcv. I tried install other mmcv by using without using the one you provided:
```
pip install -U openmim
mim install mmcv-full
```
However, this still didn't work

**Comment by vv111y** [comment]
I tried the same paths, nothing works

**Comment by justy93** [comment]
Hello @ZhengdiYu 
I am having the same issue. Can you share how you resolved this please?
Thanks and regards

**Comment by jun297** [comment]
@justy93 Hi, I resolved this issue by
1. install torch 1.9.0 with cuda 11.1
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
2. install 1.3.8 <= mmcv-full < 1.5.0 with torch 1.9.0+cu111
`pip install mmcv-full==1.4.8 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`
3. install mmdet < 3; the error above `ModuleNotFoundError: No module named 'mmengine'` occurs because the version of mmdet is too high
`pip install mmdet==2.28.2`
4. install some minor packages (mmpose 0.24, etc)
5. 
I hope it helps!

**Comment by hanctRaise** [comment]
You saved my day @jun297

**Comment by PalaashAgrawal** [comment]
@Annbless @seaman1900 @AK391 
Can you add these to the requirements file? A lot of people are facing this installation issue
